vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        product_images:
            uri_prefix: '%env(SUPABASE_URL)%/storage/v1/object/public/%env(SUPABASE_BUCKET)%/products'
            upload_destination: supabase.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product_gallery:
            uri_prefix: '%env(SUPABASE_URL)%/storage/v1/object/public/%env(SUPABASE_BUCKET)%/gallery'
            upload_destination: supabase.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
