databases:
  # 1. Base de données PostgreSQL managée
  - name: techlink-db
    plan: free
    postgresMajorVersion: 16

services:

  # 2. Application Web Docker
  - type: web
    name: techlink-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: techlink-db
          property: connectionString
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: '1'
      - key: APP_SECRET
        generateValue: true
      - key: MAILER_DSN
        value: 'gmail://doumbiabecaye7@gmail.com:pobbeotracjzlrct@default'
      - key: MAILER_FROM
        value: 'doumbiabecaye7@gmail.com'
      - key: TRUSTED_PROXIES
        value: '127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
      - key: SUPABASE_URL
        value: 'https://xxxxxxxxxxxxxxxxxxxx.supabase.co'
      - key: SUPABASE_BUCKET
        value: 'techlink'
      - key: SUPABASE_REGION
        value: 'eu-west-1'
      - key: SUPABASE_ENDPOINT
        value: 'https://xxxxxxxxxxxxxxxxxxxx.supabase.co/storage/v1/s3'
      - key: SUPABASE_ACCESS_KEY
        value: 'REMPLACEZ_MOI'
      - key: SUPABASE_SECRET_KEY
        value: 'REMPLACEZ_MOI'
