databases:
  # 1. Base de données PostgreSQL managée
  - name: mon-projet-db
    plan: free
    postgresMajorVersion: 16

services:

  # 2. Application Web Docker
  - type: web
    name: mon-projet-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mon-projet-db
          property: connectionString
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
