services:
  # 1. Base de données MariaDB (Service Privé)
  - type: pserv
    name: mon-projet-db
    env: docker
    plan: free
    image:
      url: mariadb:10.4
    disk:
      name: mariadb-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: app
      - key: MYSQL_USER
        value: app
      - key: MYSQL_PASSWORD
        generateValue: true

  # 2. Application Web Docker
  - type: web
    name: mon-projet-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_PASS
        fromService:
          name: mon-projet-db
          type: pserv
          envVarKey: MYSQL_PASSWORD
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
